services:

  hmip2mqtt_debug:
    container_name: hmip2mqtt_debug
    image: homematicip-rest-mqtt-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 src/main.py "]
    environment:
      - HMIP_CONFIG_FILE=/run/secrets/hmip_access
      - MQTT_SERVER=raspi6
      - MQTT_PORT=8883
      - MQTT_USERNAME=mqtt_explorer
      - MQTT_PASSWORD_FILE=/run/secrets/mqtt_broker_password
      - MQTT_CA_CERT_FILE=/certs/ca.crt
      - MQTT_CLIENT_CERT_FILE=/certs/client.crt
      - MQTT_CLIENT_KEY_FILE=/certs/client.key
      - MQTT_USE_TLS=true
      # - MQTT_DISABLE_SERVER_CERT=true
      - MQTT_NO_PUBLISH=false
      - MQTT_BASE_TOPIC=hmip_ug
    volumes:
      - ./demo/hmip2mqtt/config/logging.json:/config/logging.json:ro
      - ./demo/hmip2mqtt/log:/log:rw
      - ./demo/secrets/certs/ca/ca.crt:/certs/ca.crt:ro
      - ./demo/secrets/certs/hmip2mqtt/client.crt:/certs/client.crt:ro
      - ./demo/secrets/certs/hmip2mqtt/client.key:/certs/client.key:ro
    ports:
      - 5678:5678
    secrets:
      - hmip_access
      - mqtt_broker_password
#    user: 2000:2000

  mqtt_broker:
    container_name: mqtt_broker
    image: eclipse-mosquitto
    volumes:
      # Remark: :ro -> creates messages in log, so we don't use it here
      - ./demo/mqtt_broker/config/mosquitto_2.conf:/mosquitto/config/mosquitto.conf
      - ./demo/mqtt_broker/data:/mosquitto/data
      - ./demo/mqtt_broker/log:/mosquitto/log
      - ./demo/secrets/certs/ca/ca.crt:/mosquitto/certs/ca.crt
      - ./demo/secrets/certs/mqtt_broker/server.crt:/mosquitto/certs/server.crt
      - ./demo/secrets/certs/mqtt_broker/server.key:/mosquitto/certs/server.key
    networks:
      - mqtt_network
    ports:
      # - 1883:1883
      - 18883:18883  # requires username/password authentication
      - 8883:8883    # requires client certificate authentication
    restart: unless-stopped

networks:
  mqtt_network:
    driver: bridge

secrets:
  hmip_access:
    file: ./demo/secrets/hmip_access.ini
  mqtt_broker_password:
    file: ./demo/secrets/mqtt_broker_password.txt
